"""creation tables fiche et ressource

Revision ID: 8ef55fc8b660
Revises: 
Create Date: 2026-09-15 14:18:57.805523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ef55fc8b660'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.Text(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('resume', sa.Text(), nullable=False),
    sa.Column('mots_cles', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('concepts_cles', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('prerequis', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('pour_aller_plus_loin', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ressource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiche_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['fiche_id'], ['fiche.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ressource')
    op.drop_table('fiche')
    # ### end Alembic commands ###
